#!/bin/bash
#
# set a default timezon and ntupdate
#

set -e
set -u
set -o pipefail

# set the timezone
timedatectl set-timezone ${ntp_timezone}

# install ntpd
yes | aptdcon --hide-terminal --install ntp || true

# clear out the list of ntp servers
sed -i '/server.*/d' /etc/ntp.conf

# insert line comment
echo -e "\n#\n# The below was generated by ${0}\n#\n"

# iterate through a space-separated list of peers
for peer in ${ntp_peers}; do
  echo "server ${peer}" >> /etc/ntp.conf
done

service ntp restart
